sudo: false
language: php

git:
  depth: 2

php:
- 7.1
- 7.2

services:
- memcached

before_script:
- "sudo apt-get install php7-memcached"
- "phpenv config-add travis.php.ini"
- composer install

script:
- phpunit BufferTest.php
