
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm

language: php

php:
- 7.1
- 7.2

sudo: false

services:
- memcached
- mysql

before-install:
- composer self-update

install: composer install

before_script:
- php --version
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv
- echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv
- "sudo apt-get install php72-memcached"

script:
- phpunit BufferTest.php

