language: php

git:
  depth: 2

php:
- 7.1

services:
- memcached
- redis-server

before_install:
- PHP_INI=~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
- apt-get install -y php-memcached;

before_script:
- phpenv config-add travis.php.ini
- composer install

script:
- phpunit test/DataAccessor/BufferTest.php

notifications:
  email: false