sudo: required
language: php

git:
  depth: 2

php:
- 7.1
- 7.2

services:
- memcached

before_install:
- sudo apt-get update

before_script:
- sudo apt-get install -y php-memcached
- phpenv config-add travis.php.ini
- composer install

script:
- phpunit BufferTest.php

notifications:
  email: false