sudo: false
language: php

git:
  depth: 2

php:
- 7.1
- 7.2


services:
- memcached
- mysql
- redis-server

before-install:
- composer self-update
- phpenv config-add travis.php.ini

install:
- composer install

before_script:
- php --version

script:
- phpunit BufferTest.php
