sudo: required

language: php

git:
  depth: 2

php:
- 7.1

services:
- memcached

before_install:
- PHP_INI=~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo apt-get update
- sudo apt-get install -y php-memcached

before_script:
- phpenv config-add travis.php.ini
- composer install

script:
- phpunit test/DataAccessor/BufferTest.php

notifications:
  email: false