sudo: required
language: php

git:
  depth: 2

php:
- 7.1

services:
- memcached
- redis-server

before_install:
- echo no | pecl install memcached

before_script:
- phpenv config-add travis.php.ini
- composer install

script:
- phpunit test/DataAccessor/BufferTest.php

notifications:
  email: false