sudo: required
language: php

git:
  depth: 2

php:
- 7.1
- 7.2

services:
- memcached

before_script:
- pecl install memcached
- phpenv config-add travis.php.ini
- composer install

script:
- phpunit BufferTest.php
