sudo: required

language: php

git:
  depth: 2

php:
- 7.1

services:
- memcached

before_install:
- PHP_INI=~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- sudo apt-get update
- sudo apt-get install -y php-memcached

before_script:
- phpenv config-add travis.php.ini
- composer install

script:
- phpunit test/DataAccessor/BufferTest.php

notifications:
  email: false