language: php

php:
- 7.3

sudo: true

services:
- memcached
- mysql
- redis-server

before-install:
- composer self-update
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
- php --version
- cat /etc/*release
- composer install

script:
- phpunit BufferTest.php
