language: php

php:
- 7.3

sudo: true

services:
- memcached
- mysql
- redis-server

before_install:
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- composer self-update

install:
- php --version
- php -m
- cat /etc/*release
- pwd

script:
- phpunit BufferTest.php
